spring:
  application:
    name: samsam
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ssgmysql.iptime.org:3306/samsamdb
    username: samsam
    password: samsam
server:
  port: 8080

# mybatis ??

